title: Janine Santos # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br> <br> 
  I am a curious, self-starter majoring in Information Systems and minoring in Computer Science at Seattle Pacific University.
  I am on track to graduate for June of 2021 and am looking to use both my programming and design skills in my next role. <br>
  <br><br><br>
  <a href="https://www.linkedin.com/in/janinedaniellesantos/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
